# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Math Utility Repo applying CI #tên của nhóm công việc cần phải làm khi ai đó push code!!!!

on:
  push:
    branches: [ "main" ]  #Bất kì khi nào mà ai đó push code lên main
  pull_request:
    branches: [ "main" ]

jobs:                    #thì làm công việc ở dưới đây
  build:

    runs-on: ubuntu-latest     #1. Mượn 1 cái server của Mỹ, cày sãn hệ điều hành Ubuntu

    steps:                     #2. Làm thêm các bước sau trên server vừa mượn
    - uses: actions/checkout@v3  #2.1 Lấy toàn bộ code từ kho chuyển sang server
    - name: Set up JDK 17        #2.2 Mượn 1 JDK nào đó trên server  
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven    #2.3 Chuẩn bị chạy lệnh đóng gói app, chạy luôn Unit Test
      run: mvn -B package --file pom.xml

    
